name: DEV - Build

on:
  workflow_dispatch:

  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  APP_NAME: thongchai-tutorial-frontend
  CONTAINER_REPOSITORY: "acrthongchaitutorial001.azurecr.io"
  IMAGE_TAG: "0.0.1-SNAPSHOT"

jobs:
  unitest:
    name: UnitTest
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Unit test
        run: npm run test:unit
      # for vuejs npm run test:unit

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results
          path: "${{ github.workspace }}/coverage/lcov-report/*"

  analyze:
    name: SAST CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["javascript"]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]

    steps:
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
